float mapf( float x, float in_min, float in_max, float out_min, float out_max );
void limitf( float * input, const float limit );
float rcexpo( float x, float exp );
float fastsin( float x );
float fastcos( float x );
float sin_approx( float x );
float cos_approx( float x );
float atan2_approx( float y, float x );
float acos_approx( float x );
float asin_approx( float x );
